//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlerAcessoAluno.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class TB_ACESSO
    {
        [Key]
        public int COD_ACESSO { get; set; }

        [DataType(DataType.Date)] //Com esse formato eu não precisarei digitar a data apena escolho a data em um calendário e com essa formatação também não pegaremos a hora somente a data
        public string DATA { get; set; }
        [DataType(DataType.Time)] //Vai aparecer a opção pra me pode escolher a hora
        public System.TimeSpan HORA_ENTRADA { get; set; }
        [DataType(DataType.Time)]//Vai aparecer a opção pra me pode escolher a hora
        public System.TimeSpan HORA_SAIDA { get; set; }
        public Nullable<int> COD_ALUNO { get; set; }
    
        public virtual TB_ALUNO TB_ALUNO { get; set; }
    }
}
